version: '3.8'

services:
  terrad:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    hostname: terrad
    pull_policy: always
    volumes:
      - terra:/app
    networks:
      - terra
    ports:
      - '1317:1317'
      - '8080:8080'
      - '9090:9090'
      - '9091:9091'
      - '26657:26657'
  oracle:
    build:
      context: ./pseudo-feeder
      dockerfile: Dockerfile
    pull_policy: always
    depends_on:
      - terrad
    networks:
      - terra
    environment:
      TESTNET_LCD_URL: http://terrad:1317
    command: start

volumes:
  terra:

networks:
  terra:
