version: '3.8'

services:
  terrad:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang:1.20-alpine3.18
    hostname: terrad
    pull_policy: always
    volumes:
      - terra:/app
    networks:
      - terra
    ports:
      - '1317:1317'
      - '8080:8080'
      - '9090:9090'
      - '9091:9091'
      - '26657:26657'

volumes:
  terra:

networks:
  terra:
